spring:
  application:
    name: s_ai
  ai:
    deepseek:
      chat:
        model: deepseek-v4-flash
        api-key: sk-f1a8bf713fd44d00992168ab95990a2a
        base-url: https://api.deepseek.com
        temperature: 0.7
  mongodb:
    uri: mongodb://root:123456@localhost:27017/ai?authSource=admin
  data:
    redis:
      host: localhost
      port: 6379
      password: 123456
      database: 0
server:
  port: 9999

config:
  limit:
    device_call_count_prefix: "device:call_count:"
    call_count_expire_day: 1
    max_call_count: 5
  gaode:
    apikey: 86737a81711e70cf567f140423138d5a
    amap_ip_url: https://restapi.amap.com/v3/ip # 获取ip定位
    amap_weather: https://restapi.amap.com/v3/weather/weatherInfo # 获取天气信息
    amap_driving: https://restapi.amap.com/v5/direction/driving # 路径规划
    amap_walking: https://restapi.amap.com/v3/direction/walking # 路径规划
    amap_geocode: https://restapi.amap.com/v3/geocode/geo # 地址编码
    amap_road: https://restapi.amap.com/v3/traffic/status/road # 获取道路交通状态 未使用
    amap_bus: https://restapi.amap.com/v3/bus/stopid # 获取公交站点信息 未使用
    amap_etd_driving: https://restapi.amap.com/v4/etd/driving # 高级路线规划 未使用






